# Generated by Django 5.0.2 on 2024-02-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='person',
            new_name='shop_owner',
        ),
    ]
