# Generated by Django 4.1.5 on 2024-02-19 10:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_person_shop_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
