# Generated by Django 4.1.5 on 2024-02-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='area',
        ),
    ]
