# Generated by Django 5.0.2 on 2024-02-20 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_answerquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='quiz_app.question'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz_app.question'),
        ),
    ]
