# Generated by Django 5.0.2 on 2024-02-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_resultquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question'),
        ),
    ]
