# Generated by Django 5.0.2 on 2024-02-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_alter_answerquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultquiz',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_quiz', to='quiz_app.question'),
        ),
    ]
